"""Generated artefacts: the metric data dictionary and the published schemas.

Both are derived from code (the metric registry and the Pydantic models) so that the
documentation and the schema files cannot drift from what the software does. CI runs
``python scripts/generate.py --check``; a schema or metric change therefore has to be
committed together with its regenerated output, which is also where a reviewer sees the
change and where a schema-version bump is decided (``docs/SPECIFICATION.md``).
"""

from __future__ import annotations

import json
from typing import Any

import polars as pl
from pydantic import BaseModel

from vizanix_atlas.core.metrics_registry import REGISTRY, Metric, Scope
from vizanix_atlas.core.versions import METHODOLOGY_VERSION, SCHEMA_VERSION
from vizanix_atlas.models.asset import AssetAlias, AssetRelationship, CanonicalAsset
from vizanix_atlas.models.instrument import Instrument
from vizanix_atlas.models.manifest import (
    DailyCompactionReport,
    GenerationManifest,
    LatestPointer,
    SystemHealth,
)
from vizanix_atlas.models.observations import AdapterHealth
from vizanix_atlas.models.quality import QualityEvent
from vizanix_atlas.models.state import MarketState, VenueAssetState
from vizanix_atlas.mql.columns import ASSET_TABLE_COLUMNS
from vizanix_atlas.util.sample import build_sample_generation

_SCHEMA_MODELS: dict[str, type[BaseModel]] = {
    "asset": CanonicalAsset,
    "asset_alias": AssetAlias,
    "asset_relationship": AssetRelationship,
    "instrument": Instrument,
    "market_state": MarketState,
    "venue_asset_state": VenueAssetState,
    "adapter_health": AdapterHealth,
    "quality_event": QualityEvent,
    "generation_manifest": GenerationManifest,
    "latest_pointer": LatestPointer,
    "daily_compaction_report": DailyCompactionReport,
    "system_health": SystemHealth,
}


def render_json_schemas() -> dict[str, str]:
    """Return ``filename -> content`` for every published JSON Schema."""
    files: dict[str, str] = {}
    for name, model in _SCHEMA_MODELS.items():
        schema: dict[str, Any] = model.model_json_schema()
        schema["$comment"] = f"Atlas schema_version {SCHEMA_VERSION}; generated, do not edit."
        files[f"{name}.schema.json"] = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    return files


def render_arrow_schemas() -> dict[str, str]:
    """Return the published Parquet column layout of the sharded market-state table.

    Derived from a real (tiny) build rather than restated by hand, so it is exactly what
    the dataset builder writes.
    """
    from vizanix_atlas.storage.tables import (
        build_asset_market_state_table,
        build_venue_asset_state_table,
    )

    generation = build_sample_generation(extra_asset=True)
    tables: dict[str, pl.DataFrame] = {
        "asset_market_state": build_asset_market_state_table(generation.bundles, shard_count=64),
        "venue_asset_state": build_venue_asset_state_table(generation.bundles),
    }
    files: dict[str, str] = {}
    for name, frame in tables.items():
        columns = [{"name": col, "type": str(dtype)} for col, dtype in frame.schema.items()]
        files[f"{name}.arrow.json"] = (
            json.dumps(
                {"schema_version": SCHEMA_VERSION, "table": name, "columns": columns}, indent=2
            )
            + "\n"
        )
    return files


def _row(metric: Metric) -> str:
    published = metric.name in ASSET_TABLE_COLUMNS
    caveats = "; ".join(metric.caveats) if metric.caveats else ""
    cells = [
        f"`{metric.name}`",
        metric.unit.value,
        metric.dtype,
        "yes" if published else "declared",
        metric.description,
        f"`{metric.formula}`" if metric.formula else "-",
        str(metric.minimum_coverage) if metric.minimum_coverage else "",
        str(metric.minimum_observations) if metric.minimum_observations else "",
        metric.missing_semantics.value,
        caveats,
    ]
    return "| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |"


def render_metrics_markdown() -> str:
    """Render ``docs/METRICS.md`` from the metric registry."""
    published = sum(1 for m in REGISTRY if m.name in ASSET_TABLE_COLUMNS)
    lines = [
        "# Metric dictionary",
        "",
        "<!-- Generated by `python scripts/generate.py` from `core/metrics_registry.py`. Do not edit. -->",
        "",
        f"Methodology version `{METHODOLOGY_VERSION}`, schema version `{SCHEMA_VERSION}`. "
        f"The registry declares {len(REGISTRY)} metrics; {published} of them are published as "
        "queryable columns in the asset-level `market` table today (the *Published* column). "
        "*Declared* means the definition is fixed but the current dataset does not yet "
        "carry a value for it; it is listed so nobody has to guess what it will mean.",
        "",
        "Every null has a meaning (*Missing means*). Atlas never turns an unknown into a zero.",
        "",
    ]
    header = (
        "| Metric | Unit | Type | Published | Description | Formula | Min venues | Min history "
        "| Missing means | Caveats |"
    )
    divider = "|---|---|---|---|---|---|---|---|---|---|"
    for scope in Scope:
        metrics = REGISTRY.by_scope(scope)
        if not metrics:
            continue
        lines += [f"## Scope: {scope.value}", "", header, divider]
        lines += [_row(m) for m in metrics]
        lines.append("")
    return "\n".join(lines)
