"""The Universal Market Schema.

Atlas's schema is deliberately independent of every venue's naming. Nothing in this
package references a venue-specific field name; adapters translate at their own
boundary so that analytics never has to know that OKX says ``instId`` and Kraken
says ``wsname``.

The schema is exported as JSON Schema and as Arrow schemas so that another
implementation can produce or consume Atlas-compatible data without importing this
package (see ``docs/SPECIFICATION.md``).
"""

from __future__ import annotations

from vizanix_atlas.models.asset import AssetAlias, AssetRelationship, CanonicalAsset
from vizanix_atlas.models.base import AtlasModel, MutableAtlasModel
from vizanix_atlas.models.enums import (
    CollectionStatus,
    CollectionTier,
    ContractType,
    ConversionMethod,
    ExclusionReason,
    FundingSemantics,
    GenomeStatus,
    InstrumentType,
    LiquidationCapability,
    ObservationOrigin,
    OpenInterestUnit,
    OptionType,
    PriceSource,
    ReferencePriceMethod,
    RelationshipType,
    ResolutionState,
    SettlementPeriod,
    Universe,
)
from vizanix_atlas.models.instrument import Instrument
from vizanix_atlas.models.manifest import (
    BuildProvenance,
    DailyCompactionReport,
    FileEntry,
    GenerationManifest,
    LatestPointer,
    StorageReport,
    SystemHealth,
    VenueOutcome,
)
from vizanix_atlas.models.observations import (
    AdapterHealth,
    CollectionResult,
    ObservationTiming,
    OrderBookLevel,
    RawDerivativeObservation,
    RawFxObservation,
    RawInstrument,
    RawOrderBook,
    RawTicker,
)
from vizanix_atlas.models.quality import (
    Coverage,
    DataQuality,
    Freshness,
    Provenance,
    ProvenanceEntry,
    QualityEvent,
    QuoteConversion,
    WindowCoverage,
)
from vizanix_atlas.models.state import (
    AssetStateBundle,
    BasisState,
    CrowdingComponents,
    DepthBand,
    Dispersion,
    FragmentationState,
    FundingState,
    GenomeState,
    ImpactEstimate,
    LiquidationState,
    LiquidityState,
    MarketOverview,
    MarketState,
    MarketStructure,
    OpenInterestState,
    PressureComponents,
    ReferencePrice,
    ReturnsState,
    TechnicalState,
    VenueAssetState,
    VenueLiquidity,
    VolatilityState,
    VolumeState,
)
from vizanix_atlas.models.venue import RateLimitPolicy, Venue, VenueCapabilities

__all__ = [
    "AdapterHealth",
    "AssetAlias",
    "AssetRelationship",
    "AssetStateBundle",
    "AtlasModel",
    "BasisState",
    "BuildProvenance",
    "CanonicalAsset",
    "CollectionResult",
    "CollectionStatus",
    "CollectionTier",
    "ContractType",
    "ConversionMethod",
    "Coverage",
    "CrowdingComponents",
    "DailyCompactionReport",
    "DataQuality",
    "DepthBand",
    "Dispersion",
    "ExclusionReason",
    "FileEntry",
    "FragmentationState",
    "Freshness",
    "FundingSemantics",
    "FundingState",
    "GenerationManifest",
    "GenomeState",
    "GenomeStatus",
    "ImpactEstimate",
    "Instrument",
    "InstrumentType",
    "LatestPointer",
    "LiquidationCapability",
    "LiquidationState",
    "LiquidityState",
    "MarketOverview",
    "MarketState",
    "MarketStructure",
    "MutableAtlasModel",
    "ObservationOrigin",
    "ObservationTiming",
    "OpenInterestState",
    "OpenInterestUnit",
    "OptionType",
    "OrderBookLevel",
    "PressureComponents",
    "PriceSource",
    "Provenance",
    "ProvenanceEntry",
    "QualityEvent",
    "QuoteConversion",
    "RateLimitPolicy",
    "RawDerivativeObservation",
    "RawFxObservation",
    "RawInstrument",
    "RawOrderBook",
    "RawTicker",
    "ReferencePrice",
    "ReferencePriceMethod",
    "RelationshipType",
    "ResolutionState",
    "ReturnsState",
    "SettlementPeriod",
    "StorageReport",
    "SystemHealth",
    "TechnicalState",
    "Universe",
    "Venue",
    "VenueAssetState",
    "VenueCapabilities",
    "VenueLiquidity",
    "VenueOutcome",
    "VolatilityState",
    "VolumeState",
    "WindowCoverage",
]
